### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by woheller69** [woheller69/solxpect#1]
Import / Export of whole database -> V1.3
Option to sum up locations with identical lat/lon to support installations with several orientations -> V1.4
Clone location -> V1.4

Chart for hourly power for next 24h

**Comment by topcaser** [comment]
Hi, could you add a graphical chart for hourly power as well?

**Comment by topcaser** [comment]
Yeah, indeed, I would keep the hourly textual forecast  consistent with the graph. At e. G. 9 am you omit the hours before

**Comment by hanskaas** [comment]
Adding up the hours per week would be helpful when comparing different locations

**Comment by woheller69** [comment]
> Adding up the hours per week would be helpful when comparing different locations

You can try this. It shows a sum in the bottom line of hourly values. If you click on your final day it will scroll to the end.
Backup database
Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/solxpect/files/11513470/app-release.apk.zip)

**Comment by n005** [comment]
It will be helpful if we can see previous estimation in order to tweek parameters. And also it would be fine if I can choose which model from open meteo (because Météo-France for France is way better than the default one)

**Comment by woheller69** [comment]
you can switch on debug mode. Then you will see values starting at 0:00am and also cumulated values.

Doesn't Open-Meteo use Meteo-France for France?

**Comment by n005** [comment]
Ok, thanks for debug option.
I don't but the open metro seems to use another model for my location, but the current model seems accurate too.
