### ISSUE TITLE
Suggestions: Option to let stay last hour(s)

### ISSUE THREAD

**Issue by Mintulix** [woheller69/solxpect#10]
Hi, great app, thank you!
I'm just trying out to tune the data that it fits to my PV and I have two little problems:

First, when I get my real data from the server for the last hour, the prediction of that time is gone, so I always have to make screenshots from the prediction to adjust the app data to the real world. That would be easier if there was an option to show the last few hours also.

Second, the way to change the shadowing is a bit inconvenient. There are 7 trees and a chimney I want to factor in.
Go to the prediction screen, click on the sun symbol, read the actual azimut and elevation, click ok, go to the location settings, find the entry and change it (and so on). It would be much easier, if the actual location of the sun would be available directly from the shadowing table. I could of course first notice all the data from one day at a seperate location and put them into the app later, but when I do it directly, I have a better control if the changed data fits.

**Comment by woheller69** [comment]
you can switch on debug. Then you will also see past values for the current day.

Will add current sun position above the shading table.

**Comment by Mintulix** [comment]
Great! Thank you very much!

**Comment by woheller69** [comment]
You can try it here.

Backup your database
Uninstall
Remove .zip and install
Restore database

[app-release.apk.zip](https://github.com/woheller69/solxpect/files/11867388/app-release.apk.zip)

**Comment by Mintulix** [comment]
Wow, that's fast! Looks good except that now "Speichern, Schliessen, Klonen" is vertical aligned instead of horizontal like before (and you have to scroll between them). Android 8.1 (no more updates available)

**Comment by woheller69** [comment]
I only modified "Ändern" to "Speichern" 
Maybe your display does not have enough space for these 3 extra characters?

**Comment by Mintulix** [comment]
That's how it looks like. I don't know if that affects many users...

![save menu](https://github.com/woheller69/solxpect/assets/9968138/8758b54e-0ddb-49a2-b7b0-ca0a7a2c96d3)

You can scroll both sections seperately, the table and the menu.

**Comment by woheller69** [comment]
I could change "Schliessen" to "Beenden" which is shorter...
