### ISSUE TITLE
Forecasting algorithm/API

### ISSUE THREAD

**Issue by EmanuelLoos** [woheller69/solxpect#11]
I'd like to use these estimates in a bash script to automatically plan how much to charge at night, when the energy prices are low to get through until the electricity prices are low again. However, I'm having trouble finding the API and/or algorithm used for the forecasts.

**Comment by woheller69** [comment]
Maybe have a look at this project https://github.com/gvzdus/PVPrognose
They are working on an API which directly returns such a forecast for your pv system
