### ISSUE TITLE
Add max/min temperatures 

### ISSUE THREAD

**Issue by topcaser** [woheller69/solxpect#14]
Hi, I am using your app regularly to double check how much solar energy is forecasted. This is very helpful to judge whether to switch on or not the radiators e. g during the intermediate summer/winter time (highly insulated house which can safely bridge the one or another day). Anyway it would be helpful to see the min and max temperatures per day to judge how long I can bridge it without switching on the radiators. Do you think, this is feasible.

Thanks for looking into it.

**Comment by woheller69** [comment]
you can use my omWeather app to see that data

**Comment by topcaser** [comment]
Yes, I use it indeed as well. But it would be so handy if everything is in one app,even I am pretty sure that you have the data already...
