### ISSUE TITLE
negative values today

### ISSUE THREAD

**Issue by Mintulix** [woheller69/solxpect#16]
I never saw this before - the evening and night calculated values are negative (sorry for the huge picture):

![Screenshot_20240215-173035](https://github.com/woheller69/solxpect/assets/9968138/436fd431-0244-4ea3-ac97-25775d05ac8b)

I also use https://github.com/gvzdus/PVPrognose within iobroker, which uses more or less your code - also negative values today.
Is this a rare phenomenon or a real bug or...

**Comment by woheller69** [comment]
![Screenshot_20240215-200235_FREE Browser](https://github.com/woheller69/solxpect/assets/68678880/7c1b7b27-7057-4be0-b28c-b578bffddee2)
looks like a bug in Open-Meteo API

**Comment by Mintulix** [comment]
Ah, sorry, I didn't check this. I thought the first row with "0" values came from the API and the rest was calculated. It seems a fix is on the way, so this was quick! Thank you, I'll close this issue.
