### ISSUE TITLE
Keep data from last 24 hours

### ISSUE THREAD

**Issue by dexic79** [woheller69/solxpect#18]
Hello,

I would like to keep the data of the last 24 hours for reference to be able to see, where the prognosis and the real results differ. Making screenshots is unnecessary work to do, don't you think? 

I want to use the data of a really sunny day to compare with the prognosis and find out about mistakes in the settings. Especially shadows should come out very well this way. 

Thank you!

**Comment by woheller69** [comment]
you can switch on "Debug".
Then you will see the data from 0:00 of the current day

**Comment by dexic79** [comment]
What do both values stand for?

**Comment by dexic79** [comment]
Perfect! :-) Thank you!
