### ISSUE TITLE
Verbesserung-Vorschlag 

### ISSUE THREAD

**Issue by ferdlgogosch** [woheller69/solxpect#22]
Nach dem Aufruf der APP, sollte die Anzeige zur aktuellen Stunde wechseln.
Derzeit startet die Ansicht bei 0-Uhr.

**Comment by woheller69** [comment]
Das tut sie auch, wenn DEBUG ausgeschaltet ist

**Comment by ferdlgogosch** [comment]
Vielen Dank, an das habe ich nicht gedacht. Jetzt funktioniert es, lebe jetzt schon seit einem Jahr damit....
