### ISSUE TITLE
Hourly vaues should be reset for ever day

### ISSUE THREAD

**Issue by marku5** [woheller69/solxpect#23]
Bug or idea?

Main screen shows three sections:
1. Hourly values
2. Daily values as values
3. Daily values as barchart

Values in 2. and 3. are reset every day.
The sum of kWh in 1. is summarized for all shown days => These values shall as well be set to zero in midnight.

**Comment by woheller69** [comment]
the hourly sum helps finding the right pramaters by comparing with measured production values

**Comment by marku5** [comment]
To clarify: I like the hourly sum, just not the "no value reset at midnight".

**Comment by woheller69** [comment]
Please try this apk

-Backup your settings
-Uninstall
-Remove .zip and install
-Restore settings

Values are reset at midnight if not in debug mode

[app-release.apk.zip](https://github.com/user-attachments/files/16049399/app-release.apk.zip)

**Comment by marku5** [comment]
Works! Thanks for the fix/new feature!
