### ISSUE TITLE
How to translate to Spanish

### ISSUE THREAD

**Issue by Pablohn26** [woheller69/solxpect#25]
**Describe the bug**
There is no way to translate it to Spanish. Could you add localization support? (for example weblate)

**How to Reproduce**
1. Go to repository 
2. Look for Contributing guidelines
3. Look for Translating

**Expected behavior**
A link to weblate or instructions about how to contribute to translations 

**Screenshots**
Not needed

**Environment (please complete the following information):**
 - App version: Not needed
 - Android version: Not needed
 - Device: Not needed

**Comment by woheller69** [comment]
You can translate the strings here:
https://github.com/woheller69/solxpect/blob/main/app/src/main/res/values/styles.xml
and the documentation here:
https://github.com/woheller69/solxpect/blob/main/app/src/main/assets/help/help-en.html

and upload the files here or create a pull request.
