### ISSUE TITLE
Idea: Undo for editing locations

### ISSUE THREAD

**Issue by marku5** [woheller69/solxpect#5]
Editing locations
Swiping easily deletes the location
-> Add "Are you sure? Y/N" or Undo-option

**Comment by woheller69** [comment]
you can make a backup of your database

**Comment by woheller69** [comment]
Please try this. Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/solxpect/files/11292517/app-release.apk.zip)

**Comment by marku5** [comment]
Super, tnx a lot.

**Comment by marku5** [comment]
Solved
