### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by topcaser** [woheller69/solxpect#9]
Hi, I am using obtainium to install your apps. Obtainium observes github releases and informs if new versions are available. Unfortunately solxpect's latest version with apk is 1.2. I can't switch to fdroid since it is signed differently. Version 1.2 isn't able to export my pv settings. I want to kindly ask you whether you could provide a new github version that I can update and I want to ask you what your release platforms are in the future? Thanks for supporting, Bernd

**Comment by woheller69** [comment]
You can upgrade to B1.61 and export your database.
The switch to F-Droid
